### ISSUE TITLE
使用python2.7运行报错，可以请问是什么问题吗？

### ISSUE THREAD

**Issue by KivenGood** [tangsanli5201/DeepPCB#6]
Traceback (most recent call last):
  File "script.py", line 5, in <module>
    import rrc_evaluation_funcs
  File "D:\pythonWorkPlace\DeepPCB-master\evaluation\rrc_evaluation_funcs.py", line 306
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by tangsanli5201** [comment]
这个评测代码和ICDAR 2015竞赛官网保持一致，可以关注其官方代码。
